version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: tfx-cli
    versions:
    - 0.8.3
    - 0.9.0
    - 0.9.1
  - dependency-name: "@microsoft/applicationinsights-web"
    versions:
    - 2.5.11
    - 2.6.0
    - 2.6.1
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
    - 8.0.0
    - 8.1.0
  - dependency-name: roosterjs
    versions:
    - 8.0.0
    - 8.0.1
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
    - 0.5.33
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: rimraf
    versions:
    - 3.0.2
  - dependency-name: vss-web-extension-sdk
    versions:
    - 5.141.0
